### ISSUE TITLE
Error: cannot open profile file /etc/firejail/disable-programs.inc

### ISSUE THREAD

**Issue by Futureknows** [equk/torjail#1]
Upon running script from extracted torjail directory I get the following error:

> Error: cannot open profile file /etc/firejail/disable-programs.inc
> Entire dialog included below.
> 
> user@user-desktop:~/torjail$ ./torbrowser.sh
> [ OK ] starting torbrowser script
> [ OK ] torbrowser version 6.0.3 found
> [ OK ] creating torjail base folder at /home/user/.torjail
> pub   4096R/93298290 2014-12-15 [expires: 2020-08-24]
>       Key fingerprint = EF6E 286D DA85 EA2A 4BA7  DE68 4E2C 6E87 9329 8290
> uid                  Tor Browser Developers (signing key) torbrowser@torproject.org
> sub   4096R/F65C2036 2014-12-15 [expires: 2017-08-25]
> sub   4096R/D40814E0 2014-12-15 [expires: 2017-08-25]

[ OK ] signing key for torbrowser found
[ OK ] Tor Browser Developers (signing key) torbrowser@torproject.org
[ OK ] verifying files
tor-browser-linux64-6.0.3_en-US.tar.xz: OK
[ OK ] verifying gpg key
gpg: Signature made Tue 02 Aug 2016 06:22:05 AM PDT using RSA key ID D40814E0
gpg: Good signature from "Tor Browser Developers (signing key) torbrowser@torproject.org"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: EF6E 286D DA85 EA2A 4BA7  DE68 4E2C 6E87 9329 8290
     Subkey fingerprint: BA1E E421 BBB4 5263 180E  1FC7 2E1A C68E D408 14E0
[ OK ] extracting torbrowser bundle
[ WARN ] dwm does not exist in priv-home
[ WARN ] copying dwm from /usr/bin/dwm
[ OK ] starting session
Reading profile torbrowser.profile
Error: cannot open profile file /etc/firejail/disable-programs.inc
Reading profile torbrowser.profile
Error: cannot open profile file /etc/firejail/disable-programs.inc
./torbrowser.sh: line 236: 15071 Terminated              Xephyr -auth "$TORJAIL_XAUTH" -screen "$TORJAIL_RES" "$TORJAIL_DISPLAY"
[ OK ] cleaning up tmpfs
[ OK ] removing /tmp/torjail
[ OK ] session finished ...
user@user-desktop:~/torjail$

**Comment by equk** [comment]
Hi,

What version of firejail are you using?
disable-programs.inc was introduced with firejail 0.9.40

here is my commit adding disable-programs.inc (22 Jun 2016) - https://github.com/equk/torjail/commit/70bda3ae153c8190ce1cc20e04ea883f637ad7c3

If possible make sure you are running firejail 0.9.40+ (latest stable at the moment is 0.9.40)
https://firejail.wordpress.com/download-2/

If you are running firejail 0.9.40 and still have this problem, which version of linux are you running?

**Comment by Futureknows** [comment]
Sir, you are a master. I had Firejail 0.9.38.
Updated and works perfectly.
