### ISSUE TITLE
torbrowser.filter gets ignored

### ISSUE THREAD

**Issue by shellshocker** [equk/torjail#2]
Why?

Enable  the network filter specified by filename in the new net‐
work namespace. The filter file format is the  format  of  ipta‐
bles-save  and iptable-restore commands.  New network namespaces
are created using --net option. If a new network  namespaces  is
not created, --netfilter option does nothing.

From: https://firejail.wordpress.com/features-3/man-firejail/

You are doing this: firejail --profile="$TORJAIL.profile" --netfilter="$TORJAIL.filter"
But there is no new "net". So your filter gets ignored.

**Comment by equk** [comment]
Thanks for reporting this

The filter files were there from testing networking using br0 etc
