### ISSUE TITLE
checksum / gpg not matching

### ISSUE THREAD

**Issue by Hindi500** [equk/torjail#4]
Script seems to run okay however I receive the following error:

[ OK ] starting torbrowser script
[ OK ] creating torjail base folder at /home/owner/.torjail
pub   4096R/93298290 2014-12-15 [expires: 2020-08-24]
      Key fingerprint = EF6E 286D DA85 EA2A 4BA7  DE68 4E2C 6E87 9329 8290
uid                  Tor Browser Developers (signing key) <torbrowser@torproject.org>
sub   4096R/F65C2036 2014-12-15 [expires: 2017-08-25]
sub   4096R/D40814E0 2014-12-15 [expires: 2017-08-25]
sub   4096R/C3C07136 2016-08-24 [expires: 2018-08-24]

[ OK ] signing key for torbrowser found
[ OK ] Tor Browser Developers (signing key) <torbrowser@torproject.org>
[ OK ] downloading torbrowser - tor-browser-linux64-6.0.7_en-US.tar.xz
######################################################################## 100.0%
[ OK ] verifying files
tor-browser-linux64-6.0.7_en-US.tar.xz: OK
[ OK ] verifying gpg key
gpg: Signature made Wed 30 Nov 2016 11:17:48 AM CST using RSA key ID D40814E0
gpg: lookup_hashtable failed: eof
gpg: Good signature from "Tor Browser Developers (signing key) <torbrowser@torproject.org>"
gpg: lookup_hashtable failed: eof
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: EF6E 286D DA85 EA2A 4BA7  DE68 4E2C 6E87 9329 8290
     Subkey fingerprint: BA1E E421 BBB4 5263 180E  1FC7 2E1A C68E D408 14E0
[ ERROR ] checksum or gpg key did not match
[ WARN ] removing file
[ WARN ] corrupt/invalid file removed - please restart torjail

**Comment by equk** [comment]
gpg: lookup_hashtable failed: eof

Seems like there is something going on with your gpg
It could be possible your trustdb is corrupt in some way

Running  `gpg --list-keys` Should prompt to recreate trustdb if this is the case.

**Comment by Hindi500** [comment]
I've done a **gpg **--list-keys**** There did not appear to be any issues with trustdb. There were Tor keys and I removed those. Any other idease? I'd really like to use this script.
Also, what distro are you using for this? I am running Fedora 23. 

Thanks for your help and for writing this!
