### ISSUE TITLE
Error: cannot access profile file

### ISSUE THREAD

**Issue by Futureknows** [equk/torjail#5]
Script runs, downloads latest Torbrowser then returns error:

**Error: cannot access profile file**

Mint 18.2. I tried -x same problem. Same problem on notebook/desktop fresh mint and Ubuntu.

> bird@Farow ~ $ '/home/bird/Downloads/torjail-master/torbrowser.sh' 
[ OK ] starting torbrowser script
[ OK ] torbrowser version 7.0.2 found
[ OK ] creating torjail base folder at /home/bird/.torjail
pub   4096R/93298290 2014-12-15 [expires: 2020-08-24]
      Key fingerprint = EF6E 286D DA85 EA2A 4BA7  DE68 4E2C 6E87 9329 8290
uid                  Tor Browser Developers (signing key) <torbrowser@torproject.org>
sub   4096R/F65C2036 2014-12-15 [expires: 2017-08-25]
sub   4096R/D40814E0 2014-12-15 [expires: 2017-08-25]
sub   4096R/C3C07136 2016-08-24 [expires: 2018-08-24]
[ OK ] signing key for torbrowser found
[ OK ] Tor Browser Developers (signing key) <torbrowser@torproject.org>
[ OK ] verifying files
tor-browser-linux64-7.0.2_en-US.tar.xz: OK
[ OK ] verifying gpg key
gpg: Signature made Mon 03 Jul 2017 07:37:05 AM PDT using RSA key ID C3C07136
gpg: Good signature from "Tor Browser Developers (signing key) <torbrowser@torproject.org>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: EF6E 286D DA85 EA2A 4BA7  DE68 4E2C 6E87 9329 8290
     Subkey fingerprint: A430 0A6B C93C 0877 A445  1486 D148 3FA6 C3C0 7136
[ OK ] extracting torbrowser bundle
[ WARN ] dwm does not exist in priv-home
[ WARN ] copying dwm from /usr/bin/dwm
[ OK ] starting session
Error: cannot access profile file
Error: cannot access profile file
/home/bird/Downloads/torjail-master/torbrowser.sh: line 236:  8395 Terminated              Xephyr -auth "$TORJAIL_XAUTH" -screen "$TORJAIL_RES" "$TORJAIL_DISPLAY"
[ OK ] cleaning up tmpfs
[ OK ] removing /tmp/torjail
[ OK ] session finished ...

**Comment by equk** [comment]
Hi,

Is the profile file within the same folder as the script?
(torbrowser.profile)

This is what I am getting (using firejail version 0.9.48 on archlinux)

```
[ OK ] extracting torbrowser bundle
[ WARN ] dwm does not exist in priv-home
[ WARN ] copying dwm from /usr/bin/dwm
[ OK ] starting session
Reading profile torbrowser.profile
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
```

**Comment by Futureknows** [comment]
Yes profile was in the same folder... I noticed when I launch it from the local directory instead of a desktop shortcut it works fine.
Thanks!
